Changed default branch to main, added bolding to some messages for better readability

diff --git a/squashbranch b/squashbranch
--- a/squashbranch
+++ b/squashbranch
@@ -6,7 +6,7 @@
 if [ "$1" == "-h" -o "$1" == "--help" ]; then
     cat <<USAGE
 usage: squashbranch [PARENT]   Squash all changes on the current branch; PARENT
-                               defaults to "master".  Current branch must have
+                               defaults to "main".  Current branch must have
                                clean status so local changes don't get scooped
                                up in the squash.  To undo the squash prior to
                                committing:
@@ -17,38 +17,42 @@ USAGE
     exit 0
 fi
 
+Bold=`tput bold`
+Off=`tput sgr0`
+
 Status=`git status -s`
 if [ "$Status" ]; then
+  echo "${Bold}Current branch has uncommitted changes:${Off}"
   echo "This cannot distinguish between changes to be squashed and local or untracked changes; commit changes you want or stash changes you don't (including untracked files)"
   echo "$Status"
   exit 1
 fi
 
-Parent="${1:-master}"
+Parent="${1:-main}"
 BranchName=`git rev-parse --abbrev-ref HEAD`
 
-if [ "$BranchName" == "master" ]; then
-  echo "Squashing the master branch is not generally a good idea" 1>&2
+if [ "$BranchName" == "main" -o "$BranchName" == "master" ]; then
+  echo "${Bold}Squashing the $BranchName branch is not generally a good idea${Off}" 1>&2
   exit 1
 fi
 
 if [ "$Parent" == "$BranchName" ]; then
-  echo "Cannot squash $BranchName relative to itself" 1>&2
+  echo "${Bold}Cannot squash $BranchName relative to itself${Off}" 1>&2
   exit 1
 fi
 
 BranchPoint=`git merge-base "$Parent" "$BranchName"`
 BranchHashes=`git log "$BranchPoint..HEAD" --format=format:%h | tr "\n" " "`
 echo "----------------------------------------------------------------------"
-echo "Squashing back to $BranchPoint:"
+echo "${Bold}Squashing back to $BranchPoint:${Off}"
 git log "$BranchPoint~1..HEAD" --format=oneline --abbrev-commit  # Include branched commit
 echo "----------------------------------------------------------------------"
-# echo "DIDN'T REALLY SQUASH" && exit 0  # Early-exit for testing
+# echo "${Bold}DIDN'T REALLY SQUASH${Off}" && exit 0  # Early-exit for testing
 git reset "$BranchPoint"
 git add -A
 echo "----------------------------------------------------------------------"
 git status
 echo "----------------------------------------------------------------------"
-echo "Squashed: $BranchHashes"
+echo "${Bold}Squashed: $BranchHashes${Off}"
 echo "Now git commit with a message for the single commit and force-push (or undo with 'git reset --hard && git pull')"
 ###
